### ISSUE TITLE
Issues with pip installing the package

### ISSUE THREAD

**Issue by harryyeh-astro** [valboz/VBMicrolensing#1]
Hello,

Interesting package. I've been trying to download this package using pip:

<img width="569" alt="image001" src="https://github.com/user-attachments/assets/714ce73b-aa61-4982-9151-5a8fd91b5aa5">
But errors keep on occurring, I wonder if I have entered the wrong command or name after "pip install"

Below is the instructions from the GitHub page:
<img width="857" alt="image002" src="https://github.com/user-attachments/assets/7b24e122-ccea-47e9-acfb-e8f37160e701">
It tells us to download with "pip install ."

Which I suspect is not the correct line?

Please help, and thanks in advance.

-Harry

**Comment by harryyeh-astro** [comment]
Hello - Thanks a lot! It is working perfectly now. I did not see in the instructions that I need to clone the respiratory. 

Cheers!
Harry

**Comment by valboz** [comment]
Great!
